### ISSUE TITLE
[BUG]Error when starting the server

### ISSUE THREAD

**Issue by dixiatielu** [J3fftw1/LiteXpansion#123]
## Description (REQUIRED)

An error occured when starting the server.

## Steps to reproduce the Issue (REQUIRED)

Start the server with the versions in the last of the issue.

## Expected behavior (REQUIRED)

Enable the plugin properly.

## Server Log

**Here is the error log**
```
[21:33:30 WARN]: [LiteXpansion] MassFabricator - 'MASS_FABRICATOR_MACHINE' (LiteXpansion vDEV - 114 (git 061c0798)): The implemented Interface "me.mrCookieSlime.Slimefun.Objects.SlimefunItem.interfaces.InventoryBlock" has been deprecated. Check the documentation for more details!
[21:33:30 WARN]: [LiteXpansion] You can report this warning here: https://github.com/J3fftw1/LiteXpansion/issues
[21:33:30 WARN]: [LiteXpansion] Generator - 'GENERATOR' (LiteXpansion vDEV - 114 (git 061c0798)): The implemented Interface "me.mrCookieSlime.Slimefun.Objects.SlimefunItem.interfaces.InventoryBlock" has been deprecated. Check the documentation for more details!
[21:33:30 WARN]: [LiteXpansion] You can report this warning here: https://github.com/J3fftw1/LiteXpansion/issues
[21:33:30 ERROR]: Error occurred while enabling LiteXpansion vDEV - 114 (git 061c0798) (Is it up to date?)
java.lang.NoSuchFieldError: NETHER_GOLD_ORE
        at dev.j3fftw.litexpansion.machine.Macerator.registerDefaultRecipes(Macerator.java:71) ~[?:?]
        at me.mrCookieSlime.Slimefun.Objects.SlimefunItem.abstractItems.AContainer.register(AContainer.java:236) ~[?:?]
        at dev.j3fftw.litexpansion.ItemSetup.registerMachines(ItemSetup.java:81) ~[?:?]
        at dev.j3fftw.litexpansion.ItemSetup.init(ItemSetup.java:54) ~[?:?]
        at dev.j3fftw.litexpansion.LiteXpansion.onEnable(LiteXpansion.java:59) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.15.2.jar:git-Paper-390]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:380) ~[patched_1.15.2.jar:git-Paper-390]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483) ~[patched_1.15.2.jar:git-Paper-390]
        at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugin(CraftServer.java:472) ~[patched_1.15.2.jar:git-Paper-390]
        at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugins(CraftServer.java:386) ~[patched_1.15.2.jar:git-Paper-390]
        at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:488) ~[patched_1.15.2.jar:git-Paper-390]
        at net.minecraft.server.v1_15_R1.DedicatedServer.init(DedicatedServer.java:298) ~[patched_1.15.2.jar:git-Paper-390]
        at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:909) ~[patched_1.15.2.jar:git-Paper-390]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]

```

## Environment (REQUIRED)

![image](https://user-images.githubusercontent.com/29675002/103458545-352a1f80-4d44-11eb-9b0d-6e80d2c6ad6f.png)

**Comment by J3fftw1** [comment]
Wrong issue tracker please use
https://github.com/Slimefun-Addon-Community/LiteXpansion/issues?q=is%3Aopen+is%3Aissue
